### ISSUE TITLE
Deploy.sh has some broken api commands

### ISSUE THREAD

**Issue by ondrae** [GSA-TTS/all_sorns#146]
It has some commands to create new apps, which we've never used.
https://github.com/18F/all_sorns/blob/main/.cloud-gov/deploy.sh#L49

The correct command is `cf v3-create-app all_sorns`

It will also need a step to bind the database to the app.`cf bind-service all_sorns all-sorns-db`

if this a new app, then the apply-manifest call wont work because the code hasn't been pushed up yet.
`cf v3-apply-manifest -f .cloud-gov/manifest.yml`

**Comment by folksgl** [comment]
Is there a reason to be using the `v6` version of the CF CLI as opposed to the `v7` version? 

All of the `v3-<xyz>` commands are explicitly listed as **experimental**, and should probably be left out of any scripts that need to be reliable long-term.

It's also unclear to me how lines 49+50 are functionally different from a normal `cf push` that will "Push a new app or sync changes to an existing app". If there's no difference or a `cf push` is the intention behind those lines I think that's probably the simplest fix.

**Comment by mogul** [comment]
`deploy.sh` has been refactored out of existence.
