### ISSUE TITLE
Documentation assumes homebrew package manager

### ISSUE THREAD

**Issue by folksgl** [GSA-TTS/all_sorns#304]
Only providing instructions for those who use `homebrew` as their package manager typically just includes those who are using Apple hardware. There are a wide range of package managers available, and in my experience the overwhelming majority of developers tend to use `apt`. While changing or supplementing the documentation with `apt` related instructions will still leave _some_ users having to fend for themselves, the `apt` package manager most closely aligns with the Ubuntu-based cloud foundry runtime that this project is deployed to.

**Comment by mogul** [comment]
`homebrew` works fine in Ubuntu (and hence WSL under Windows) now.
